config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'likes/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  root "static_pages#home"
  get '/help', to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get '/signup', to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  #micropostは削除しました
  resources :relationships,       only: [:create, :destroy]
  
  #like拡張機能
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :micropost, counter_cache: :likes_count
  belongs_to :user
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @micropost = Micropost.find(params[:micropost_id])
    @like = Like.create(user_id: current_user.id, micropost_id: params[:micropost_id])
    @likes = Like.where(micropost_id: params[:micropost_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, micropost_id: params[:micropost_id])
    like.destroy
    @likes = Like.where(micropost_id: params[:micropost_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if micropost.like_user(current_user.id) %>
  <%= button_to micropost_like_path(likes, micropost_id: micropost.id), method: :delete, id: "like-button", remote: true do %> 
    <%= image_tag("icon_heart.png") %>
    <span>
      <%= micropost.likes.count %>
    </span>
  <% end %>
<% else %>
  <%= button_to micropost_likes_path(micropost),id: "like-button", remote: true do %>  
    <%= image_tag("icon_gray_heart.png") %>
    <span>
      <%= micropost.likes.count %>
    </span>
  <% end %>
<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes, like: @like}) %>");

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes }) %>");